CREATE TABLE `buku_peraturan_desa` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `jenis_peraturan_desa` varchar(255) DEFAULT NULL,
 `no_dan_tgl_ditetapkan` varchar(255) DEFAULT NULL,
 `tentang` varchar(255) DEFAULT NULL,
 `uraian_singkat` varchar(255) DEFAULT NULL,
 `tgl_kesepakatan_peraturan_desa` date DEFAULT NULL,
 `no_dan_tgl_dilaporkan` varchar(255) DEFAULT NULL,
 `no_dan_tgl_diundangkan_dalam_lembaran_desa` varchar(255) DEFAULT NULL,
 `no_dan_tgl_diundangkan_dalam_berita_desa` varchar(255) DEFAULT NULL,
 `ket` varchar(255) DEFAULT NULL,
 `created_at` datetime DEFAULT NULL,
 `created_by` varchar(255) DEFAULT NULL,
 `updated_at` datetime DEFAULT NULL,
 `updated_by` varchar(255) DEFAULT NULL,
 `verif_lurah` varchar(20) DEFAULT NULL,
 `verif_lurah_at` datetime DEFAULT NULL,
 `berkas` varchar(255) DEFAULT NULL,
 PRIMARY KEY (`id`)
);

CREATE TABLE `buku_keputusan_kepala_desa` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `no_tgl_keputusan_kepala_desa` varchar(255) DEFAULT NULL,
 `tentang` varchar(255) DEFAULT NULL,
 `uraian_singkat` varchar(255) DEFAULT NULL,
 `no_tgl_dilaporkan` varchar(255) DEFAULT NULL,
 `ket` varchar(255) DEFAULT NULL,
 PRIMARY KEY (`id`)
);

CREATE TABLE `buku_aparat_pemerintah_desa` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `nama` varchar(255) DEFAULT NULL,
 `niap` varchar(255) DEFAULT NULL,
 `nip` varchar(255) DEFAULT NULL,
 `jenis_kelamin` varchar(255) DEFAULT NULL,
 `ttl` varchar(255) DEFAULT NULL,
 `agama` varchar(255) DEFAULT NULL,
 `pangkat_golongan` varchar(255) DEFAULT NULL,
 `jabatan` varchar(255) DEFAULT NULL,
 `pendidikan_terakhir` varchar(255) DEFAULT NULL,
 `no_tgl_keputusan_pengangkatan` varchar(255) DEFAULT NULL,
 `no_tgl_keputusan_pemberhentian` varchar(255) DEFAULT NULL,
 `ket` varchar(255) DEFAULT NULL,
 PRIMARY KEY (`id`)
);

CREATE TABLE `buku_agenda` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `status_surat` date DEFAULT NULL,
 `sm_no` varchar(255) DEFAULT NULL,
 `sm_tgl` date DEFAULT NULL,
 `sm_pengirim` varchar(255) DEFAULT NULL,
 `sm_isi` varchar(255) DEFAULT NULL,
 `sk_no` varchar(255) DEFAULT NULL,
 `sk_tgl` date DEFAULT NULL,
 `sk_ditunjukkan` varchar(255) DEFAULT NULL,
 `sk_isi` varchar(255) DEFAULT NULL,
 `ket` varchar(255) DEFAULT NULL,
 `created_at` datetime DEFAULT NULL,
 `created_by` varchar(255) DEFAULT NULL,
 `updated_at` datetime DEFAULT NULL,
 `updated_by` varchar(255) DEFAULT NULL,
 PRIMARY KEY (`id`)
) 

CREATE TABLE `buku_ekspedisi` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `tgl_pengiriman` date DEFAULT NULL,
 `tgl_no_surat` varchar(255) DEFAULT NULL,
 `isi_singkat_surat` varchar(255) DEFAULT NULL,
 `ditunjukkan_kpd` varchar(255) DEFAULT NULL,
 `ket` varchar(255) DEFAULT NULL,
 `created_at` datetime DEFAULT NULL,
 `created_by` varchar(255) DEFAULT NULL,
 `updated_at` datetime DEFAULT NULL,
 `updated_by` varchar(255) DEFAULT NULL,
 PRIMARY KEY (`id`)
)

CREATE TABLE `buku_inventaris_kekayaan_desa` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `jenis_brng_bangunan` varchar(255) DEFAULT NULL,
 `abb_dibeli_sendiri` int(11) DEFAULT NULL,
 `bantuan_pemeritah` int(11) DEFAULT NULL,
 `bantuan_prov` int(11) DEFAULT NULL,
 `bantuan_kab_kota` int(11) DEFAULT NULL,
 `abb_sumbangan` int(11) DEFAULT NULL,
 `baik_awalthn` int(11) DEFAULT NULL,
 `rusak_awalthn` int(11) DEFAULT NULL,
 `rusak_hps` int(11) DEFAULT NULL,
 `dijual_hps` int(11) DEFAULT NULL,
 `disumbangkan_hps` int(11) DEFAULT NULL,
 `tgl_hapus` date DEFAULT NULL,
 `baik_akhirthn` int(11) DEFAULT NULL,
 `rusak_akhirthn` int(11) DEFAULT NULL,
 `ket` varchar(255) DEFAULT NULL,
 `created_at` datetime DEFAULT NULL,
 `created_by` varchar(255) DEFAULT NULL,
 `updated_at` datetime DEFAULT NULL,
 `updated_by` varchar(255) DEFAULT NULL,
 `berkas` varchar(255) DEFAULT NULL,
 `ver_kepala_desa_at` datetime DEFAULT NULL,
 `ver_kepala_desa` varchar(255) DEFAULT NULL,
 PRIMARY KEY (`id`)
)

CREATE TABLE `buku_tnh_desa` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `nama_perorangan_bdn_hkm` varchar(255) DEFAULT NULL,
 `jml` float DEFAULT NULL,
 `sdh_serti_hm` float DEFAULT NULL,
 `sdh_serti_hgb` float DEFAULT NULL,
 `sdh_serti_hp` float DEFAULT NULL,
 `sdh_serti_hgu` float DEFAULT NULL,
 `sdh_serti_hpl` float DEFAULT NULL,
 `blm_serti_ma` float DEFAULT NULL,
 `blm_serti_vi` float DEFAULT NULL,
 `blm_serti_tn` float DEFAULT NULL,
 `non_pertanian_perumahan` float DEFAULT NULL,
 `non_pertanian_dagang_jasa` float DEFAULT NULL,
 `non_pertanian_kantor` float DEFAULT NULL,
 `non_pertanian_industri` float DEFAULT NULL,
 `non_pertanian_fasilitas_umum` float DEFAULT NULL,
 `pertanian_sawah` float DEFAULT NULL,
 `pertanian_tegalan` float DEFAULT NULL,
 `pertanian_kebun` float DEFAULT NULL,
 `pertanian_ternak` float DEFAULT NULL,
 `pertanian_hutan` float DEFAULT NULL,
 `pertanian_hutan_lindung` float DEFAULT NULL,
 `pertanian_mutasi` int(11) DEFAULT NULL,
 `pertanian_tanah_kosong` float DEFAULT NULL,
 `pertanian_lain` float DEFAULT NULL,
 `ket` varchar(255) DEFAULT NULL,
 `created_at` datetime DEFAULT NULL,
 `created_by` varchar(255) DEFAULT NULL,
 `updated_at` datetime DEFAULT NULL,
 `updated_by` varchar(255) DEFAULT NULL,
 PRIMARY KEY (`id`)
)

CREATE TABLE `buku_tnh_kas_desa` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `asal_tnh_kas` varchar(255) DEFAULT NULL,
 `no_serti_letterc_persil` varchar(255) DEFAULT NULL,
 `luas` float DEFAULT NULL,
 `kelas` varchar(255) DEFAULT NULL,
 `peroleh_asli_milik_desa` float DEFAULT NULL,
 `bantuan_pem` float DEFAULT NULL,
 `bantuan_prov` float DEFAULT NULL,
 `bantuan_kab_kota` float DEFAULT NULL,
 `peroleh_lain` float DEFAULT NULL,
 `tgl_peroleh` date DEFAULT NULL,
 `jenis_sawah` float DEFAULT NULL,
 `jenis_tegal` float DEFAULT NULL,
 `jenis_kebun` float DEFAULT NULL,
 `jenis_tambak` float DEFAULT NULL,
 `jenis_darat` float DEFAULT NULL,
 `patok_ada` float DEFAULT NULL,
 `patok_tdkada` float DEFAULT NULL,
 `papan_ada` float DEFAULT NULL,
 `papan_tdkada` float DEFAULT NULL,
 `lokasi` varchar(255) DEFAULT NULL,
 `peruntukkan` varchar(255) DEFAULT NULL,
 `mutasi` int(11) DEFAULT NULL,
 `ket` varchar(255) DEFAULT NULL,
 `created_at` datetime DEFAULT NULL,
 `created_by` varchar(255) DEFAULT NULL,
 `updated_at` datetime DEFAULT NULL,
 `updated_by` varchar(255) DEFAULT NULL,
 PRIMARY KEY (`id`)
)